services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - angular-dist:/usr/share/nginx/html
    depends_on:
      - backend
  
  backend:
    build:
      context: ./backend/Backend.Api
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    expose:
      - "8080"

  angular-build:
    build:
      context: ./ClientApp
      dockerfile: Dockerfile
    volumes:
      - angular-dist:/app/dist/client-app/browser

volumes:
  angular-dist:
