services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - angular-dist:/usr/share/nginx/html
    depends_on:
      - backend
    deploy:
      resources:
          limits:
            cpus: "0.4"
            memory: 256M 
          reservations:
            cpus: "0.2"
            memory: 128M
  backend:
    build:
      context: ./backend/Backend.Api
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    expose:
      - "8080"
    depends_on:
      - database
    deploy:
      resources:
          limits:
            cpus: "0.8"
            memory: 512M
          reservations:
            cpus: "0.4"
            memory: 256M

  angular-build:
    build:
      context: ./ClientApp
      dockerfile: Dockerfile
    volumes:
      - angular-dist:/app/dist/client-app/browser

  database:
    image: postgres:alpine
    environment:
      #TODO: TO BE MOVED TO SECRETS
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    deploy:
      resources:
          limits:
            cpus: "0.4"
            memory: 256M 
          reservations:
            cpus: "0.2"
            memory: 128M
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
volumes:
  angular-dist:
